2025-03-02 12:50:51,972 INFO    MainThread:14244 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 12:50:51,973 INFO    MainThread:14244 [wandb_setup.py:_flush():67] Configure stats pid to 14244
2025-03-02 12:50:51,975 INFO    MainThread:14244 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-03-02 12:50:51,976 INFO    MainThread:14244 [wandb_setup.py:_flush():67] Loading settings from /content/drive/MyDrive/MSc/Year 1/Semester A/למידה עמוקה לבעיות פיזיקאליות 361.2.2330/Project/curriculum/wandb/settings
2025-03-02 12:50:51,977 INFO    MainThread:14244 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 12:50:51,978 INFO    MainThread:14244 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /content/drive/MyDrive/MSc/Year 1/Semester A/למידה עמוקה לבעיות פיזיקאליות 361.2.2330/Project/curriculum/wandb/offline-run-20250302_125051-goylpnfb/logs/debug.log
2025-03-02 12:50:51,979 INFO    MainThread:14244 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /content/drive/MyDrive/MSc/Year 1/Semester A/למידה עמוקה לבעיות פיזיקאליות 361.2.2330/Project/curriculum/wandb/offline-run-20250302_125051-goylpnfb/logs/debug-internal.log
2025-03-02 12:50:51,979 INFO    MainThread:14244 [wandb_init.py:init():761] calling init triggers
2025-03-02 12:50:51,979 INFO    MainThread:14244 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-02 12:50:51,980 INFO    MainThread:14244 [wandb_init.py:init():784] starting backend
2025-03-02 12:50:52,189 INFO    MainThread:14244 [wandb_init.py:init():788] sending inform_init request
2025-03-02 12:50:52,203 INFO    MainThread:14244 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-02 12:50:52,207 INFO    MainThread:14244 [wandb_init.py:init():803] backend started and connected
2025-03-02 12:50:52,210 INFO    MainThread:14244 [wandb_init.py:init():896] updated telemetry
2025-03-02 12:50:52,221 INFO    MainThread:14244 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 12:50:52,353 INFO    MainThread:14244 [wandb_init.py:init():995] starting run threads in backend
2025-03-02 12:50:52,797 INFO    MainThread:14244 [wandb_run.py:_console_start():2377] atexit reg
2025-03-02 12:50:52,798 INFO    MainThread:14244 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-02 12:50:52,799 INFO    MainThread:14244 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-02 12:50:52,799 INFO    MainThread:14244 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-02 12:50:52,807 INFO    MainThread:14244 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-02 12:50:52,808 INFO    MainThread:14244 [wandb_run.py:_config_callback():1261] config_cb None None {'k_squared': 3, 'n_points': 10000}
2025-03-02 12:50:52,839 WARNING MsgRouterThr:14244 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 12:50:52,841 INFO    MsgRouterThr:14244 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
